export const TYPES = {
  UserRepository: Symbol.for('UserRepository'),
  GetUser: Symbol.for('GetUser'),
  CreateUser: Symbol.for('CreateUser'),
  LoginUser: Symbol.for('LoginUser'),
  UserController: Symbol.for('UserController'),
  Routes: Symbol.for('Routes'),
  Server: Symbol.for('Server'),
  TokenService: Symbol.for('TokenService'),
  Logger: Symbol.for('Logger'),
  RequestLogger: Symbol.for('RequestLogger'),
  RequestHandler: Symbol.for('RequestHandler'),
  UUID: Symbol.for('UUID'),
  Database: Symbol.for('Database'),
  Crypto: Symbol.for('Crypto'),
  FactoryCreateUser: Symbol.for('FactoryCreateUser'),
  CreateUserController: Symbol.for('CreateUserController'),
};
